<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506003637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE historique_equipement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, champ_modifie VARCHAR(255) NOT NULL, ancienne_valeur VARCHAR(255) NOT NULL, nouvelle_valeur VARCHAR(255) NOT NULL, equipement_id INT NOT NULL, panne_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C0E07C1A806F0F5C ON historique_equipement (equipement_id)');
        $this->addSql('CREATE INDEX IDX_C0E07C1A65B7B5BD ON historique_equipement (panne_id)');
        $this->addSql('CREATE TABLE historique_ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, champ_modifie VARCHAR(255) NOT NULL, ancienne_valeur VARCHAR(255) NOT NULL, nouvelle_valeur VARCHAR(255) NOT NULL, ticket_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5EE20DFF700047D2 ON historique_ticket (ticket_id)');
        $this->addSql('CREATE TABLE intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, commentaire TEXT DEFAULT NULL, ticket_id INT NOT NULL, technicien_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D11814AB700047D2 ON intervention (ticket_id)');
        $this->addSql('CREATE INDEX IDX_D11814AB13457256 ON intervention (technicien_id)');
        $this->addSql('CREATE TABLE ligne_intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite_utilisee INT NOT NULL, intervention_id INT NOT NULL, stock_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_69C654648EAE3863 ON ligne_intervention (intervention_id)');
        $this->addSql('CREATE INDEX IDX_69C65464DCD6110 ON ligne_intervention (stock_id)');
        $this->addSql('CREATE TABLE mouvement_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, date_mouvement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, quantite INT NOT NULL, stock_id INT NOT NULL, effectue_par_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_61E2C8EBDCD6110 ON mouvement_stock (stock_id)');
        $this->addSql('CREATE INDEX IDX_61E2C8EBFAE26142 ON mouvement_stock (effectue_par_id)');
        $this->addSql('CREATE TABLE panne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_panne VARCHAR(255) NOT NULL, gravite VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE personnel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricule VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, fonction VARCHAR(255) NOT NULL, date_embauche DATE NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6BCF3DE12B2DC9C ON personnel (matricule)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6BCF3DEE7927C74 ON personnel (email)');
        $this->addSql('CREATE TABLE responsable (service VARCHAR(255) NOT NULL, date_nomination DATE NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sla (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, temps_max_resolution INT NOT NULL, temps_max_reponse INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_article VARCHAR(255) NOT NULL, quantite INT NOT NULL, seuil_min INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE technicien (specialite VARCHAR(255) NOT NULL, niveau_competence VARCHAR(255) NOT NULL, disponible BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) NOT NULL, priorite VARCHAR(255) NOT NULL, description TEXT NOT NULL, cree_par_id INT NOT NULL, traitee_par_id INT NOT NULL, panne_id INT NOT NULL, sla_id INT NOT NULL, equipement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA3FC29C013 ON ticket (cree_par_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA33338F50D ON ticket (traitee_par_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA365B7B5BD ON ticket (panne_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA37A2CC8C4 ON ticket (sla_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3806F0F5C ON ticket (equipement_id)');
        $this->addSql('CREATE TABLE ticket_modifie_par (ticket_id INT NOT NULL, personnel_id INT NOT NULL, PRIMARY KEY (ticket_id, personnel_id))');
        $this->addSql('CREATE INDEX IDX_E1ADBA4B700047D2 ON ticket_modifie_par (ticket_id)');
        $this->addSql('CREATE INDEX IDX_E1ADBA4B1C109075 ON ticket_modifie_par (personnel_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE historique_equipement ADD CONSTRAINT FK_C0E07C1A806F0F5C FOREIGN KEY (equipement_id) REFERENCES equipement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_equipement ADD CONSTRAINT FK_C0E07C1A65B7B5BD FOREIGN KEY (panne_id) REFERENCES panne (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_ticket ADD CONSTRAINT FK_5EE20DFF700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814AB700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814AB13457256 FOREIGN KEY (technicien_id) REFERENCES technicien (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_intervention ADD CONSTRAINT FK_69C654648EAE3863 FOREIGN KEY (intervention_id) REFERENCES intervention (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_intervention ADD CONSTRAINT FK_69C65464DCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mouvement_stock ADD CONSTRAINT FK_61E2C8EBDCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mouvement_stock ADD CONSTRAINT FK_61E2C8EBFAE26142 FOREIGN KEY (effectue_par_id) REFERENCES personnel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE responsable ADD CONSTRAINT FK_52520D07BF396750 FOREIGN KEY (id) REFERENCES personnel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE technicien ADD CONSTRAINT FK_96282C4CBF396750 FOREIGN KEY (id) REFERENCES personnel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3FC29C013 FOREIGN KEY (cree_par_id) REFERENCES personnel (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA33338F50D FOREIGN KEY (traitee_par_id) REFERENCES responsable (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA365B7B5BD FOREIGN KEY (panne_id) REFERENCES panne (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA37A2CC8C4 FOREIGN KEY (sla_id) REFERENCES sla (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3806F0F5C FOREIGN KEY (equipement_id) REFERENCES equipement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_modifie_par ADD CONSTRAINT FK_E1ADBA4B700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket_modifie_par ADD CONSTRAINT FK_E1ADBA4B1C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE historique_equipement DROP CONSTRAINT FK_C0E07C1A806F0F5C');
        $this->addSql('ALTER TABLE historique_equipement DROP CONSTRAINT FK_C0E07C1A65B7B5BD');
        $this->addSql('ALTER TABLE historique_ticket DROP CONSTRAINT FK_5EE20DFF700047D2');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814AB700047D2');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814AB13457256');
        $this->addSql('ALTER TABLE ligne_intervention DROP CONSTRAINT FK_69C654648EAE3863');
        $this->addSql('ALTER TABLE ligne_intervention DROP CONSTRAINT FK_69C65464DCD6110');
        $this->addSql('ALTER TABLE mouvement_stock DROP CONSTRAINT FK_61E2C8EBDCD6110');
        $this->addSql('ALTER TABLE mouvement_stock DROP CONSTRAINT FK_61E2C8EBFAE26142');
        $this->addSql('ALTER TABLE responsable DROP CONSTRAINT FK_52520D07BF396750');
        $this->addSql('ALTER TABLE technicien DROP CONSTRAINT FK_96282C4CBF396750');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3FC29C013');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA33338F50D');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA365B7B5BD');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA37A2CC8C4');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3806F0F5C');
        $this->addSql('ALTER TABLE ticket_modifie_par DROP CONSTRAINT FK_E1ADBA4B700047D2');
        $this->addSql('ALTER TABLE ticket_modifie_par DROP CONSTRAINT FK_E1ADBA4B1C109075');
        $this->addSql('DROP TABLE equipement');
        $this->addSql('DROP TABLE historique_equipement');
        $this->addSql('DROP TABLE historique_ticket');
        $this->addSql('DROP TABLE intervention');
        $this->addSql('DROP TABLE ligne_intervention');
        $this->addSql('DROP TABLE mouvement_stock');
        $this->addSql('DROP TABLE panne');
        $this->addSql('DROP TABLE personnel');
        $this->addSql('DROP TABLE responsable');
        $this->addSql('DROP TABLE sla');
        $this->addSql('DROP TABLE stock');
        $this->addSql('DROP TABLE technicien');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_modifie_par');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
